---
title: "Bayes Start"
subtitle: "Eine Einführung in die Bayes-Statistik"
author: "Sebastian Sauer"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
   
---


# Kapitel 1

**Was ist Inferenz?**

## Lernziele

[Lernziele Kapitel 1](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-1)

## Lektüre

*Regression and other stories*, Kap. 1

## PDF-Skript

[PDF-Skript Kapitel 1](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema1-WasistInferenz.pdf)


## Quellcode zum Skript

[Quellcode zum Skript Kapitel 1](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema1-WasistInferenz.Rmd)

## Aufgaben



[Aufgaben Kapitel 1, Teil a](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema1-Teil1-Übungsaufgaben1.html)



[Aufgaben Kapitel 1, Teil b](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema1-Teil2-Übungsaufgaben1.html)

## Lösungen

[Lösungen Kapitel 1, Teil a](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema1-Teil1-Übungsaufgaben1-Loesungen.html)

[Lösungen Kapitel 1, Teil b](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema1-Teil2-Übungsaufgaben1-Loesungen.htm)

## Videos

[Videos Kapitel 1, Teil a](https://youtube.com/playlist?list=PLRR4REmBgpIGK0OsNOmSArj8kNgtMVYj9)

[Videos Kapitel 1, Teil b]( https://youtube.com/playlist?list=PLRR4REmBgpIFCZd_CWmpRhzX2QoYDEx8K)

---

# Kapitel 2

**Wissen updaten**

## Lernziele

[Lernziele Kapitel 2](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-2)

## Lektüre

*Statistical Rethinking*, Kap. 2




## PDF-Skript

[PDF-Skript Kapitel 2](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema1-kleineModelle.pdf)


## Quellcode zum Skript

[Quellcode zum Skript Kapitel 2](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema1-kleineModelle.pdf)

## Aufgaben

[Aufgaben Kapitel 2](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema2-Übungsaufgaben1.html)

## Lösungen 

[Lösungen Kapitel 2](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema2-Übungsaufgaben1.html)

## Videos

[Videos Kapitel 2](https://youtube.com/playlist?list=PLRR4REmBgpIFVdesZy-AkPdbO0fhnpJO-)








---

# Kapitel 3

**Die Posteriori-Verteilung**

## Lernziele

[Lernziele Kapitel 3](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-3)

## Lektüre

*Statistical Rethinking*, Kap. 3


## HTML-Skript

[HTML-Skript Kapitel 3](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema3-Post-befragen.html#1)

## PDF-Skript

[PDF-Skript Kapitel 3](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema3-Post-befragen.pdf)

## Quellcode

[Quellcode zum Skript 3](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema3-Post-befragen.Rmd)

## Aufgaben

[Aufgaben Kapitel 3](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema3-Übungsaufgaben1.html)


## Lösungen

[Lösungen Kapitel 3](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema3-Loesungen.html)

## Videos

[Videos Kapitel 3](https://youtube.com/playlist?list=PLRR4REmBgpIE5-LMlRzSCkXVc2_4pZD2u)

---









---

# Kapitel 4

**Gauss-Modelle**

## Lernziele

[Lernziele Kapitel 4](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-4)

## Lektüre

*Statistical Rethinking*, Kap. 4.1-4.3


## HTML-Skript

[HTML-Skript Kapitel 4](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema4-Gaussmodelle.html#1)

## PDF-Skript

[PDF-Skript Kapitel 4](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema4-Gaussmodelle.pdf)

## Quellcode zum Skript

[Quellcode zum Skript 4](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema4-Gaussmodelle.Rmd)

## Aufgaben

[Aufgaben Kapitel 4](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema4-Übungsaufgaben1.html)


## Lösungen

[Lösungen Kapitel 4](http://sebastiansauer.github.io/bayes-start/Aufgaben/Thema3-Loesungen.html)

## Videos

[Videos Kapitel 4](https://youtube.com/playlist?list=PLRR4REmBgpIFhjaRCvDtM91QdZiqOCThX)

---






# Kapitel 5

**Lineare Regression**

## Lernziele

[Lernziele Kapitel 5](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-5)

## Lektüre

*Statistical Rethinking*, Kap. 4.4, *ROS*, Kap. 9.2


## HTML-Skript

[HTML-Skript Kapitel 5](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema5-Lineare-Modelle.html#1)

## PDF-Skript

[PDF-Skript Kapitel 5](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema5-Lineare-Modelle.pdf)

## Quellcode zum Skript

[Quellcode zum Skript 4](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema5-Lineare-Modelle.Rmd)

## Aufgaben




## Lösungen



## Videos



---








# Kapitel 6

**Deskriptive Forschungsfragen**

## Lernziele

[Lernziele Kapitel 6](https://sebastiansauer.github.io/bayes-start/Lernziele.html#kapitel-6)

## Lektüre

*ROS*, 10.1-10.4, 11.1-11.4, 11.6


## HTML-Skript

[HTML-Skript Kapitel 6](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema6-Deskriptive-Forschungsfragen.html#1)

## PDF-Skript

[PDF-Skript Kapitel 6](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema6-Deskriptive-Forschungsfragen.pdf)

## Quellcode zum Skript

[Quellcode zum Skript 6](https://sebastiansauer.github.io/QM2-Folien/Themen/QM2-Thema6-Deskriptive-Forschungsfragen.Rmd)

## Aufgaben




## Lösungen



## Videos



---
