---
title: "Lernziele"
subtitle: "Bayes Start"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
---



# Übergreifende Lernziele


Nach Absolvieren dieses Kurses sollten Lernis folgende Lernziele erreicht haben.


- Die theoretischen Grundlagen - inklusive dem Rechtfertigungszusammenhang und die Grenzen des Verfahrens - erklären können
- Bayes-Modellierung im Rahmen von Regressionsmodellen anwenden können für typische, angewandte Forschungsfragen
- Kausalfragen in statistische Designs umsetzen und auswerten können

# Lernziele pro Kapitel


## Kapitel 1

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- die Definition von Inferenzstatistik sowie Beispiele für inferenzstatistische Fragestellungen nennen
- zentrale Begriffe nennen und in Grundzügen erklären
- den Nutzen von Inferenzstatistik nennen
- erläutern, in welchem Zusammenhang Ungewissheit zur Inferenzstatistik steht
- auch anhand von Beispielen erklären, was ein statistisches Modell ist
- die Grundkonzepte der Regression angeben
- Unterschiede zwischen klassischer und Bayes-Inferenz benennen
- Vor- und Nachteile der klassischen vs. Bayes-Inferenz diskutieren
- Die grundlegende Herangehensweise zur Berechnung des p-Werts informell erklären können
- Wahrscheinlichkeit definieren und relevante Begriffe anführen und in Grundzügen erklären
- einfache Fragen aus der Wahrscheinlichkeitstheorie berechnen


## Kapitel 2

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...


- die Unterschiede zwischen einem Modell und der Realität erkären und anhand eines Beispiels verdeutlichen
- das rechnerische Prinzip des "Wissen updaten" an einem konkreten Beispiel erläutern und nachrechnen
- Die Posteriori-Wahrscheinlichkeit eines einfaches Bayes-Modells berechnen, in R programmieren und die wesentlichen Schritte erläutern



## Kapitel 3

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...


- erläutern und mit R berechnen, wie man eine Posteriori-Verteilung erstellt
- erläutern und mit R berechnen, wie man Stichproben aus der Posteriori-Verteilung zieht
- wesentliche Forschungsfragen, wie nach Intervallen und Punktschätzwerten, anhand der Stichproben aus der Posteriori-Verteilung beantworten
- erläutern, was eine Posteriori-Prädiktiv-Verteilung ist, und inwiefern Sie vor Übergewissheit schützt
- eine Modellprüfung für das Beispiel aus dem Unterricht anhand der Posteriori-Prädiktiv-Verteilung durchführen



## Kapitel 4

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- erklären, was eine Verteilung ist und welche Varianten es gibt
- wissen um den ontologischen Bedingungszusammenhang einer Normalverteilung; sie können erklären, wie eine Normalverteilung entsteht
- ein Gaussmodell spezifizieren und R berechnen
- an Beispielen verdeutlichen, wie sich eine vage bzw. eine informationsreiche Priori-Verteilung auf die Posteriori-Verteilung auswirkt


## Kapitel 5

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- die Post-Verteilung für einfache lineare Modelle in R berechnen
- zentrale Informationen zu Modellparametern - wie Lage- oder Streuungsmaße und auch Schätzintervalle - aus der Post-Verteilung herauslesen
- künftige, laut Modell zu erwartende Beobachtungen mit der PPV simulieren


## Kapitel 6

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- typische, deskriptive Forschungsfragen spezifizieren als Regression
- Forschungsfragen in Regressionsterme übersetzen
- typische Forschungsfragen auswerten


## Kapitel 7

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- Bayes-Modellierung in einen angewandten Kontext anwenden können und die Grenzen aufzeigen können
- aktuelle Themen - am Beispiel hier der Corona-Pandemie - aufgreifen können und zentrale Statistiken nachprüfen können


## Kapitel 8

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...


- erklären, wann eine Kausalaussage gegeben eines DAGs berechtigt ist
- die "Atome" der Kausalität eines DAGs benennen
- "kausale Hintertüren" schließen



## Kapitel 9


Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...

- Regressionsmodelle für binäre AV berechnen
- einen Logit in Wahrscheinlichkeit umrechnen
- logistische Regressionsmodelle interpretieren und kritisieren





